name = "pipclock"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[site]
bucket = "dist/client"

[env.production]
routes = [
  { pattern = "pipclock.bittere.workers.dev", zone_name = "workers.dev" }
]

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
